### PR TITLE
Implements support to define the owner of the virtualenv directories.

### PR DESCRIPTION
**Pull request by prla**
Thank you for the role! Here's a suggestion for supporting explicitly setting the owner of the virtualenv directories that get created.

### CODE REVIEW

**Comment by klen** [comment]
I like the idea.

What do you think about use `become_user: "{{item.user|default(ansible_ssh_user)}}"`?

**Comment by prla** [comment]
That by itself would break using Ansible 2.0 as described [here](http://docs.ansible.com/ansible/intro_inventory.html#list-of-behavioral-inventory-parameters). So, another suggestion.

On `defaults.yml`:

``` yaml
python_virtualenv_user : "{{ ansible_ssh_user }}" # can be changed if Ansible 2.0
```

And on `python.yml`:

``` yaml
"{{item.user|default(python_virtualenv_user)}}"
```

If you agree, I'll update my PR.

**Comment by klen** [comment]
Nice, I agree.

**Comment by ahelal** [comment]
Any update on merging this ?

**Pull request merged**
